### ISSUE TITLE
Swapping two numbers using bitwise XOR

### ISSUE THREAD

**Issue by dibyendu415** [JGEC-Winter-of-Code-JWoC/JWoC_Algorithms#25]

**Comment by bhagatsunny96** [comment]
I want to contribute to this issue.

**Comment by bhagatsunny96** [comment]
I would like to contribute to this issue

**Comment by bhagatsunny96** [comment]
I want to contribute to this issue

**Comment by gr33nm0nk2802** [comment]
i would like to contribute

**Comment by richard937** [comment]
@bhagatsunny96 go-ahead

**Comment by richard937** [comment]
@gr33nm0nk2802 as he claimed first I can't assign it to, please look for other issues

**Comment by Raja-11sep** [comment]
I want to solve this issue.
